### ISSUE TITLE
templates for issue creation

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#1]
I propose to test the following templates to creat issues on:
* bug
* epic
* documentation
[issue-Templates.zip](https://github.com/Orange-OpenSource/ods-ios/files/7862710/issue-Templates.zip)

**Comment by julien-deramond** [comment]
While we wait for a default branch to be created in this repository, I've fixed some errors in the `.yml` files and tried it in a GitHub test repository.
You can see them in action: https://github.com/julien-deramond/github-repository-test/issues/new/choose
Their modified source code is in https://github.com/julien-deramond/github-repository-test/tree/main/.github/ISSUE_TEMPLATE

**Comment by B3nz01d** [comment]
j'ai corriger quelques éléments dans les 3 fichiers. Par contre j'ai une question, les labels ne sont pas automatiquement pris depuis le fichier? car ils ne sont pas tous présent en utilisant le templat
[issue-Templates2.zip](https://github.com/Orange-OpenSource/ods-ios/files/7863074/issue-Templates2.zip)

**Comment by julien-deramond** [comment]
> issue-Templates2.zip

OK I'll update the GitHub test repository with your proposal

> Par contre j'ai une question, les labels ne sont pas automatiquement pris depuis le fichier? car ils ne sont pas tous présent en utilisant le templat

I think they must be created before in the repo. I'll try that.

**Comment by B3n-d1v3** [comment]
Mince je me rend compte que je ne suis reparti de tes corrections

**Comment by B3nz01d** [comment]
j'ai essayé de créer les update dans le git directement... dis moi si c'est bon pour toi

**Comment by julien-deramond** [comment]
> j'ai essayé de créer les update dans le git directement... dis moi si c'est bon pour toi

Yep :ok_hand: I merged the 3 of them.

**Comment by B3nz01d** [comment]
new templates are good to go
