### ISSUE TITLE
[Bug]: Components > Card - Progress Indicator

### ISSUE THREAD

**Issue by mccart77** [Orange-OpenSource/ods-ios#100]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 10

### OS Version

iOS 15.3.1

### App version

0.2.0

### Describe the issue

The incorrect thumbnail image is being used on the Progress Indicator card

![image](https://user-images.githubusercontent.com/89084974/166740461-d8c4690c-4eac-4575-a8b4-e15c56a9e587.jpeg)

### Expected Behavior

Replace with new image for iOS Progress bar

currently waiting on the new image to be created by Yomna (on leave until 08.05.22)

SM - 19.05.22 New thumbnails created and added to Teams Files

**Comment by ludovic35** [comment]
@mccart77 what is the name off the thumb for Edit Text category

**Comment by mccart77** [comment]
@ludovic35 I've requested this new thumbnail be created, I expect it will be ready and available early next week, probably Monday.

**Comment by mccart77** [comment]
Just updated and added some new and missing thumbnails

**Comment by B3nz01d** [comment]
card illustration has been updated
