### ISSUE TITLE
[Bug]: Progress Indicator page

### ISSUE THREAD

**Issue by mccart77** [Orange-OpenSource/ods-ios#101]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 10

### OS Version

iOS 15.3.1

### App version

0.2.0

### Describe the issue

Position of the progress indicator is left aligned and should be centre aligned

![image](https://user-images.githubusercontent.com/89084974/166740620-452b11c3-8d12-4633-b70e-9a9bd8c1a0bc.jpeg)

### Expected Behavior

align progress indicator to the centre

**Comment by B3nz01d** [comment]
this was tested ok
