### ISSUE TITLE
[Bug]: Module - Card collection - name

### ISSUE THREAD

**Issue by mccart77** [Orange-OpenSource/ods-ios#103]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 10

### OS Version

iOS 15.3.1

### App version

0.2.0

### Describe the issue

Name is incorrect should be 'Card View'

![image](https://user-images.githubusercontent.com/89084974/166837360-8100cdad-ea4a-40ff-8bfe-01a44b45fea1.jpeg)
![image](https://user-images.githubusercontent.com/89084974/166837381-1339672e-d87b-44f0-b4a9-c3fd9e04e62d.jpeg)
### Expected Behavior

update name to "Card collections"

**Comment by jlchee** [comment]
Available in build 0.2.0 (1651828612)

**Comment by B3nz01d** [comment]
This change was performed on the card in the Module page but not in the page itself (still named ListCard). The name of the card and the name of the page should be the same.

**Comment by B3nz01d** [comment]
based on comment on the 21st of June the name was update to  "Card collections".  In the version I test build 1661895006 the name was updated to "Card View".
A new card was updated to correct this at #219
