### ISSUE TITLE
[Doc]: GitHub about information

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ods-ios#11]
### Documentation Location

Not really in the documentation but rather [in the GitHub repository](https://github.com/Orange-OpenSource/ods-ios).

### Current issue

The text in the "About" section is written in French and should be in English.

![Capture d’écran 2022-02-07 à 08 02 03](https://user-images.githubusercontent.com/17381666/152740496-4ac34874-3532-4326-a380-f2b3137ca312.png)

### Expected Correction

Text must be written in English.

**Comment by B3nz01d** [comment]
@julien-deramond I do not seem to have access to change this part, but here is a text proposition:
An Orange Design System code implementation for iOS that provides a component library and code examples.

**Comment by jlchee** [comment]
an other proposition : A SwiftUI component library with code examples for Orange Design System
