### ISSUE TITLE
Update the Bottom Sheet with chips in all components using it

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#123]
# Bottom Sheets updates

## Requirement

**As a** user of the demo app
**I want** to be able to customize a component example
**So That** I can easily switch the various option and still see the component updating

## General description
A new design has been created to display the options with witch to customize a component, it is nw using the chips to be able to select and un select options. The objective is to apply this new mechanism/design to all the component allowing the customization visualization.

## Implementation Tasks
- [ ] Bottom Sheet Update in Cards page
- [x] Bottom Sheet Update in Chips page
- [x] Bottom Sheet Update in Lists page

**Comment by ludovic35** [comment]
Already done on List and chips pages

**Comment by Tayebsed93** [comment]
Problem with Voice Over

**Comment by Tayebsed93** [comment]
Voice Over : 
1. correct the vocalization of the decorative image in the header
2. Items visually identified as headers must be declared to the Accessibility API as such. (accessibilityTraitHeader) 
https://a11y-guidelines.orange.com/fr/mobile/ios/conception/#titre-et-en-tete
