### ISSUE TITLE
Demo App Clean-up

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#124]
## General description
Before we confirm a release of the lib that would include a corresponding version of the app, we need to correct a few things in the app:

## Implementation Tasks
- [x] Hide the Search tab until the content in it has been created
- [x] Add in the latest components illustrations
- [x] Make sure that all components names are consistent 
  - between the DSM name
  - the card component name
  - the component title in the page description
  - the code documentation title
- [x] the guidelines still have some empty items

**Comment by B3nz01d** [comment]
@mccart77 Any other items to add before the release?

**Comment by B3nz01d** [comment]
The update was not performed in the documentation as well

**Comment by ludovic35** [comment]
Quelle documentation ?

**Comment by jlchee** [comment]
The documentation will be updated at the end of the sprint (you can test dev documentation by using a local jeckyl server)
