### ISSUE TITLE
[Bug]: about > version numéro update 

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#136]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

Any

### OS Version

Any

### App version

V0.2.0 (1654767623)

### Describe the issue

The about page of the qualif app does not show the detailed app version

![Uploading FAEC0302-0E92-4E9D-BB92-18A005ABBDD1.jpeg…]()

### Expected Behavior

In the about page of the qualif demo app add in the version :
* the detailed build number
* the qualif label

**Comment by ludovic35** [comment]
i can't see the Uploading FAEC0302-0E92-4E9D-BB92-18A005ABBDD1.jpeg image.
Can you give me the position of the qualif label and build number

**Comment by ludovic35** [comment]
@B3nz01d @mccart77 what do you think about that ? Can we merge it like it is ?
