### ISSUE TITLE
[Bug]: Typograpy style  addition

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#155]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

any

### OS Version

any

### App version

v0.4.0 - b1656365390

### Describe the issue

the full list of typography examples is duplicating the example and the style 2 times. It's a bit difficult to understand the page the firsm time you arrive on it.

### Expected Behavior

the list separate out the exemple and the style name. I propose:
* to add in the word "style" to explaine the style naming 
* to show a text example instead of the name of the style

it could look like this:

### Lorem ipsum dolor
`style: largeTitle`

#### Morbi posuer
`style: title1`

##### ipsum at
`style: title2`

**Comment by mccart77** [comment]
I agree, adding the 'style' label to the style name helps with this screen, it also aligns better with how we display the fonts on Android.

**Comment by B3nz01d** [comment]
The update should be ONLY on the "style: " label addition and not on the renaming of the texts examples.
