### ISSUE TITLE
[feature]: Add small and Title first card

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ods-ios#182]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### As a

user of the sdk

### ... I want to

to use a component providing a :
- small card (Image, title and subtitle)
- card with title first 

IMPORTANT : NEED DESIGN BEFORE CODING

### ... so that I can

display cards depending the context of information

**Comment by Tayebsed93** [comment]
**Thumbnail and Image**: This is a decorative image
The rule is therefore not to vocalize the image with Voice Over

Screenshot : 


![IMG_19B778C3A8A8-1](https://user-images.githubusercontent.com/20354434/198998139-9dc02659-95c3-42bf-b548-e66328641f71.jpeg)

**Comment by Tayebsed93** [comment]
ok accessbility
