### ISSUE TITLE
[feature]: Update ODSChipPicker API to seperate zero or one element in the single selection

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ods-ios#198]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### As a

Developper

### ... I want to

Create an ODSChipPicker for a single selection without providing an optional value for non zero selection.

### ... so that I can

.

**Comment by B3nz01d** [comment]
I cannot test in the app... ;)

**Comment by ludovic35** [comment]
@B3nz01d For sure, we need to think about a dedicated page illustrating the usage of ODSChipPicker
