### ISSUE TITLE
Update the Button page to list the available button types

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#222]
# Button page

## Requirement

**As a** user of the demo app
**I want** to be able to select the buttons variants
**So That** I can access all of it's states

## General description
As demoed during Sprint Review 12 in Android the objective is to introduce a list selector to present the various button variants. Then each page would present that various states of that variant.

## UI specifications
The list of the variants to use is (confirmed with @mccart77 to gather the 2 inital tiles into one : "Buttons"):
* Important buttons
* Functional buttons
* Filled buttons
* Outlined buttons
* Text buttons (or Label  buttons)
* Icon buttons

**Comment by B3nz01d** [comment]
After a discussion with @ludovic35  & @Gui114um3  we propose to update the names to: 
* Important buttons
* Medium button ( Filled buttons)
* Low button (Outlined buttons)
* Functional buttons
* Text buttons (or Label buttons)
* Icon buttons

**Comment by jlchee** [comment]
After discussion with @ludovic35 and @B3nz01d , we propose ro update the names to :

**Comment by ludovic35** [comment]
After Weekly design meeting

This is new types of buttons:

- Highest emphasis button (Name to be confirmed)
- High emphasis button (previously: Filled buttons)
- Medium emphasis button (previously: Outlined buttons)
- Low emphasis button (previously: Text buttons or Label buttons)
- Functional (positive & negative option)
- Icon buttons (iOS - Maybe in android)
- Toggle buttons ( only android)
	
In the demo app the list items should propose the technical element name as a subtitle for each button example
 
In iOS you would be creating the following objects:

- ODSButton	
- ODSButtonFunctional
- ODSButtonIcon

For Android the names will be aligned with the android default object names

**Comment by ludovic35** [comment]
@B3nz01d @mccart77 Can you review the text for all variant pages of butons ?
@Gui114um3 Can you update zeppo with those texts ?
