### ISSUE TITLE
Use the SmallCard in the Demo app for component

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ods-ios#237]

**Comment by Tayebsed93** [comment]
**Image**: This is a decorative image
The rule is therefore not to vocalize the image with Voice Over

Same bug :
https://github.com/Orange-OpenSource/ods-ios/issues/182

**Comment by Tayebsed93** [comment]
@ludovic35 ok for me

**Comment by Tayebsed93** [comment]
ok accessibility
