### ISSUE TITLE
Update the Small Card description page

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#249]
# Small Card page

## Requirement

**As a** user of the demo app
**I want** to be able to select the small buttons variant
**So That** I can access the example and see the available options

## General description
The Small card page should propose only one card with a bottom sheet to allow the user to show/hide the subtitle with 

## UI specifications
The bottom sheet should propose only the following option:
* "Subtitle" with a toggle switch to turn on / off

**Comment by Tayebsed93** [comment]
bug accessibility ticket : https://github.com/Orange-OpenSource/ods-ios/issues/299
