### ISSUE TITLE
Guidelines - Typography text description updates

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#257]
The existing text is too long and should be shortened:

- [ ] define the new text
- [ ] update the text in the page description

**Comment by ludovic35** [comment]
@B3nz01d Peux-tu valider les textes des écrans suivants, stp ?:
Buttons: zpl.io/z8Blw74
Buttons emphasis : https://zpl.io/g8Dog6R
Button functional : https://zpl.io/Amd9OWe
Button icon: https://zpl.io/Q0OLMQP

Typo screen: https://zpl.io/Q0xvP8n

**Comment by B3nz01d** [comment]
* for typography: "Apple proposes built-in text styles based on the Apple Dynamic Types and using the native typeface San Francisco for all Latin, Greek and Cyrillic alphabets. To create you application you should use the following updated styles: "
* for Buttons: content is ok except for the shaped word
