### ISSUE TITLE
refactor the Chips v2

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#262]
The target is to show only one variant "Chips demo" with a link to a new page with a customization bottom sheet to allow:
* "Type" - choice chips
  * "Input" (default)
  * "Choice"
  * "Action" 
  * "Filter"
* "disabled" - toggle defaulted to off

The user experience should allow the following on each chips type:
* Input:
  * Initial state: 
    * a text description before the chips: "The user input searches are transformed into chips that can be added or deleted."
    * should show multiple chips with the close trailing icon. 
  * behavior: 
    * bottom customization: Adds under the type a new selection 
      * "Leading" - choice chips
        * "none"
        * "avatar"
        * "icon"
    * When the user taps to close the tag, it disappears.
    * Each time the input selection is tapped the full list should show again
  * Proposed input chips: "action", "comedy", "family". 

* Choice: 
  * Initial state: 
    * a text description before the chips: "The chips allow the user to select only one items within the proposed items."
    * should show multiple chips where only one can be selected at a time. 
  * Proposed choices: "tiger" (default), "Red Fox", "Orangutan", "Clownfish",  "Tamarin"
 
* Action 
  * Initial state: 
    * a text description before the chips: "The user can initiate actions by tapping on a chip."
    * should show one chip with a leading icon
  * behavior: 
  * Proposed actions chips: "like" (using the heart solaris icon), "bookmark" (using the bookmark fill solaris icon), "share" (using the share solaris icon)

* Filter
  * Initial state: 
    * a text description before the chips: "In a search by tags us user can activated the chips upon will."
    * the list of chips are presented. 
  * behavior: When the use taps on one items it is switched state from unselected to selected. More then one item can be selected at the same time
    * bottom customization: Adds under the type a new selection 
      * "Leading" - choice chips
        * "none"
        * "avatar"
  * Proposed filters: "carrot" (selected), "apricot", "butternut", "mango", "nectarine"

**Comment by ludovic35** [comment]
On  DSM (https://zeroheight.com/3b9fee398/v/latest/p/67a9e8-chips/b/604d19) there is not such types of chips.
Is there a specific design for each type of chip ?
Do we need to decider a chips as button with a specific design ?
Do we need to propose component to display a list of chip (input chips, filter, ...)

**Comment by ludovic35** [comment]
Choice Chip
@mccart77 Reagarding figma specification : 
![image](https://github.com/Orange-OpenSource/ods-ios/assets/15976893/7b4fefc6-0eb1-4567-b2fe-9a1e5d134134)

Q1 : what is the design for the press action on the seleced state ?
Q2 : is it possible to have choice chip disabled in the selected state ?
