### ISSUE TITLE
Update the Progress indicator variant list selection

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#265]
The target is to show the following variants 
* "Progress bar demo" 
* "Activity indicator"

Each page will show the related component

**Comment by ludovic35** [comment]
The label is part of the component or additional label in the demo app ?

**Comment by ludovic35** [comment]
as mention in apple guideline we should use: determinate and indeterminate :
https://developer.apple.com/design/human-interface-guidelines/components/status/progress-indicators

Regarding Label: 
Natively for Indeterminate, the label is under the wheel, do we want to keep it on the right ? What about RTL ?

Regarding determinate style:
Natively it is possible to display it with linear or circular style

**Comment by B3nz01d** [comment]
cool, it looks good
