### ISSUE TITLE
Update the Slider variant list selection

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#266]
The target is to show only one variant "sliders demo" with a link to a new page with a customization bottom sheet to allow:
* "Labeled (Side icons)" - switch on
* "Value" - switch off
*  "Stepped"  - switch off

**Comment by B3nz01d** [comment]
the value information describing the data value is not considered as part of the components.
@Tayebsed93  is it ok not to display the value for the accessibility understanding?

**Comment by ludovic35** [comment]
What is expected effect with the Stepped switch ?
