### ISSUE TITLE
Update the Text field variant list selection

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#267]
The target is to show the following variant 
* "Text field demo" with a link to a new page with a customization bottom sheet to allow
  * Capitalization: choice chips:
    * none (default)
    * characters
    * words
    * sentences

* "Secure Field"

* "Text Editor" with a link to a new page with a customization bottom sheet to allow
  * Capitalization: choice chips:
    * none (default)
    * characters
    * words
    * sentences

**Comment by ludovic35** [comment]
@B3nz01d  doit on gérer aussi le type de key board ?
