### ISSUE TITLE
[Bug]: [Accessibility] Use the SmallCard in the Demo app for component

### ISSUE THREAD

**Issue by Tayebsed93** [Orange-OpenSource/ods-ios#275]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 13 pro max

### OS Version

iOS 16.0.2

### App version

v0.7.0

### Describe the issue

Image: This is a decorative image
The rule is therefore not to vocalize the image with Voice Over

https://github.com/Orange-OpenSource/ods-ios/issues/237

### Expected Behavior

do not vocalize a decorative image

**Comment by ludovic35** [comment]
@Tayebsed93 Do we consider always the image as decorative. User can't never associate a label to describe the content, right ?

**Comment by Tayebsed93** [comment]
> @Tayebsed93 Do we consider always the image as decorative. User can't never associate a label to describe the content, right ?

@ludovic35 in my opinion I consider that it is a decorative image. However for this case we can discuss it. If you think the image is not decorative I accept but in accessibility it is recommended to describe the image
Exemple : 
```
monLabel.accessibilityLabel = @"Description de l'image";
monLabel.accessibilityHint = @"Ceci est un commentaire supplémentaire.";
```

Source : https://a11y-guidelines.orange.com/en/mobile/ios/development/#text-alternatives

**Comment by ludovic35** [comment]
In that case, it means that the SDK should do nothing on the Image (not disable accessibility). But the application providing the Image should apply those accessibility elements.

**Comment by Tayebsed93** [comment]
oh yes.. if it is technically feasible to propose the 2 solutions that would be great. You are right i am in favor of this idea

**Comment by Tayebsed93** [comment]
Ok for me

**Comment by Tayebsed93** [comment]
ok accessibility
