### ISSUE TITLE
[Doc]: add a favicon to the documentation

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#296]
### Documentation Location

All doc pages

### Current issue

there is no favicon

### Expected Correction

add the orange small logo favicon

**Comment by paulinea** [comment]
@ludovic35 To help you implementing this one, with Julien, we included everything necessary in the ODS Jekyll theme: favicons assets and head modifications. 
But I had to do some modifications on Android side and I think this is the same for you. 
In our docs directory we overridden the head of the Jekyll theme so I had to move the `<style>` content from the `_includes/head.html` to the `_layouts/main.html` and then remove `_includes/head.html` file. You can take a look to our repository.
