### ISSUE TITLE
ODS > Component > Tool Bar

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#31]
# Tool Bar

## Requirement

**As a** developer
**I want** to insert a Tool Bar
**So That** I will get this ready to use component compatible with Orange design specifications and a11y requirements

[DSM staging reference](https://orange.zeroheight.com/styleguide/s/77612/p/11ec51-tool-bar/b/526183)

## General description
the page will propose to the user to describe the component and allow to see the implementation in action.

#### Component
For the component description please refer to the DSM updates

##### Description page
![ScreenShot195](https://user-images.githubusercontent.com/62606284/161217713-02e56e21-132f-40ae-85a4-9e04ee82a980.png)

* title: "Tool bar"
* image: TBD
* Text: intro text in the DSM
* Core field:  a list of the possible variants that when you click will open a page where the user will see the tool bar in action. each item is clickable and will only display an action validation feedback.

##### Example page
The component is shown as for the tabs example page.
The customization bottom sheet should allow:
* Type: choice chip (lable -icon)
* Number of items:  stepper 
  * option for icons: from 2-5
  * option for labels: from 2-3 

TBD: to check if there is 1 or 2 variant in the code

### Variants
(To be confirmed if technically the component is différent when using labels or icons or if it is the same
#### Component
* NA

### Internationalization
NA

### Interaction
* All: 
  * 
* Touch: 
  * Nothing Specific
* Keyboard: 
  * Nothing specific

### Animations
* default OS animation

### Visual Accessibility
* taken into account within the design creation process

### Usage Accessibility
* (?) Focus order - NA
* (?) Focus loss expected behavior - NA
* (?) Screen Reader - default OS behavior
* (?) Switch Control

## Implementation tasks
-

## Related tasks
-

**Comment by ludovic35** [comment]
@mccart77 @B3nz01d For button with text, font is body and not body bold (as ODSButton), Right ?
If yes it means i con not use ODSButton which low emphasis here.

**Comment by mccart77** [comment]
@ludovic35 - Yes it is body, so you are correct.
