### ISSUE TITLE
Slider with step < 1, value is not well computed

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ods-ios#313]

**Comment by Tayebsed93** [comment]
@ludovic35 J'ai testé l'accessibilité dans son ensemble pour ce ticket.

j'ai trouvé 2 anomalies avec Voice Over : 

1. les icônes du volume sont vocalisés : est-ce voulu ? à mon sens, nous pouvons les considérer comme des images décoratives car elles n'apportent pas d'informations importantes ; et donc les ignorer avec le lecteur d'écran. 

2. impossible d'incrémenter/décrémenter la valeur de 0.5 en 0.5 avec Voice Over en activant le paramètre (Speed 0.5) : est-ce réalisable techniquement ? 

Le reste me semble ok au niveau de l'accessibilité. 
Veux-tu que j'ouvre un ticket de bug ?

**Comment by ludovic35** [comment]
@Tayebsed93 j'ai créé l'issue #385 avec ces bugs
concernant la question 1. je suis d'accord avec toi. Je désactive la localisation. 
Par contre, si ce sont des valeurs, faut il les vocaliser ?

**Comment by B3nz01d** [comment]
This cannot be tested in the app
