### ISSUE TITLE
Card, manage Tap on Action area 1

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ods-ios#319]

**Comment by ludovic35** [comment]
@mccart77 @B3nz011 d in card title first, do we consider the header a part of the area 1 ?
In small card, the area is all the card ?
Need illustration in DSM.

**Comment by mccart77** [comment]
> @mccart77 @B3nz011 d in card title first, do we consider the header a part of the area 1 ? In small card, the area is all the card ? Need illustration in DSM.

Yes, i think this is a point that needs to be changed, because in Android the header in part of the primary action area, so it should be the same for iOS. A visual has been added to the DSM specification to describe this.
