### ISSUE TITLE
ODS > Component > Bottom Sheet

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#325]

**Comment by ludovic35** [comment]
1. Tap on Grabber, order to change size of bottom sheet is:
small, medium, large, small...

2. Option BottomSheet demo in fullscreen cover page (no mortal bar). add a button with chevron < and name of the previous page (Expanding)

3. Change wording in page of variants (add a "s"on Sheet: Bottom. For Variant entry, rename to "Expanding" and "Standard")

**Comment by ludovic35** [comment]
There are some known issues created in :
https://github.com/Orange-OpenSource/ods-ios/issues/407
