### ISSUE TITLE
ODS > Component > List section Header Updates

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#416]
# Requirements
**As a Developer** using the ODS Library
**I want to** be able to use the list component
**So that** I can add sections to the list

# Content description
The current list description Page will be updated so that:
* the customization bottom sheet will include a new toggle switch labeled "Sections Headers"
* the list in the page will update to show at least 2 categories (could use the recipe category (catID) to show this)

# Technical requirements
* the list header will be used to set up this feature

**Comment by B3nz01d** [comment]
Based on today's weekly:
* the section options are: "Header" "Title" and "Footer"
  * The title option can only be used alone, if a user selects header the title option is deselected
  * Header and footer can be selected at the same time
* Add "content" customization option in the "list" options
  * "list item" to select a list using list items
  * "cards" to show a list of cards
*  style (choice chips)
  * grouped
  * plain
  * Sidebar
*

**Comment by ludovic35** [comment]
@B3nz01d Should we do the same on ListItemSelection ?

**Comment by B3nz01d** [comment]
the demo that has been shown today is using the good design examples.
The sidebar selection should use the corresponding OS code.
the sections should be using the food categories to show the demo
