### ISSUE TITLE
ODS-Guideline > Typography

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#42]
# Typography Page

Screens : https://zpl.io/JEzKZen

## Requirement

**As a** developer
**I want** to be able to see the available Typography available in the ODS Library
**So That** I see the names of the typos to use and understand their size  results in the code

[DSM reference](https://system.design.orange.com/0c1af118d/p/54fe27-typography/b/718199)

## General description
The page will propose to the user to describe the various typos available for this OS in the guidelines and support the light/dark switch.

#### Component
The Typographies will be the ones available in the Library for the developper to use

#### App Page
* the main page still needs to be designed

### Variants
NA

### States
NA

### Internationalization
To be treated later

### Interaction
* All: 
    * none
* Touch: 
    * Nothing Specific
* Keyboard: 
    * Nothing Specific

### Animations
* NA

### Visual Accessibility
* taken into account within the design creation process

### Usage Accessibility
* (?) Focus order - from left to right  / ---inverted in R2L mode--- _(this will not be added in the first iteration of the creation of this component)_
* (?) Focus loss expected behavior - NA
* (?) Screen Reader - read only the Label alt description and not the color rectangle
* (?) Switch Control

## Implementation tasks
- [ ] Task 1
- [ ] Task 2

## Related tasks
- [ ] Task 1
- [ ] Task 2

**Comment by B3nz01d** [comment]
looks ok to me, @mccart77 can you confirm?

**Comment by mccart77** [comment]
Just one comment; some of the typography names have the font weight included and some of them do not. For example, 'Large Title' has not font weight but 'Callout Regular' has. 

In the DSM we show the weight for each one but not as part of the name.

**Comment by B3nz01d** [comment]
I have logged a dedicated ticket #155 to finalize this page for me

**Comment by Tayebsed93** [comment]
is it possible to give me zeplin access?

**Comment by Tayebsed93** [comment]
looks ok to me :)
