### ISSUE TITLE
About integration in the demo app

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#422]
Feedback to be updated on the app's own about page (test from vv0.13.0):
* in the share content 
  * A: when I perform a "copy" the content has the url duplicated witch is not the case in the message option
  * B: use this new content: 
    * "You will find the Orange Design System Mobile App that provides examples of design implementations at: http://oran.ge/dsapp"
* C: in the App News the current version information is not available
* D: in the terms and condition there are a lot of special characters that are not correctly shown
*  for the accessibility statement @Tayebsed93 can you provide the correct elements to be used?

Other feedback to the about module demo
* E: the Accessibility statement empty page should provide the following text: "The Accessibility statement can be generated using the Orange's V11ydette:  https://la-va11ydette.orange.com/"
* F: the rate this app example should open the appstore url: https://www.apple.com/app-store/

**Comment by ludovic35** [comment]
The C. will be handled by https://github.com/Orange-OpenSource/ods-ios/issues/422

**Comment by ludovic35** [comment]
The A. will be handled by https://github.com/Orange-OpenSource/ods-ios/issues/435
