### ISSUE TITLE
[Bug]: Color Token issues

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#423]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

Any

### OS Version

Any

### App version

v0.13.0

### Describe the issue

The colors provided in the guidelines are not correct

### Expected Behavior

Here are the corresponding colors to the existing tokens at Orange:
* Light mode
  * Background = White 100 = #FFFFFF
  * Accent Primary = Orange 200 = #F16E00
  * Functional Positive = Forest 200 = #228722
  * Functional Negative = Fire 200 = #CD3C14
  * Functional Information = Water 200 = #4170D8
  * Functional warning = Sun 100 = #FFCC00

* Dark mode
  * Background = Black 900 = #000000
  * Accent Primary = Orange 100 = #FF7900
  * Functional Positive = Forest 100 = #32C832
  * Functional Negative = Fire 100 = #D53F15
  * Functional Information = Water 100 = #527EDB
  * Functional warning = Sun 100 = #FFCC00

* Other colors are the same for Both Light and Dark are from the reference palette an are:
  * Blue
    * Blue 100 - #b5e8f7 
    * Blue 200 - #80ceef 
    * Blue 300 - #4bb4e6 
    * Blue 400 - #3e9dd6 
    * Blue 500 - #237eca
    * Blue 600 - #085ebd 
  * Green  
    * Green 100 - #b8ebd6 
    * Green 200 - #84d5af 
    * Green 300 - #50be87 
    * Green 400 - #27a971 
    * Green 500 - #198c51 
    * Green 600 - #0a6e31 
  * Pink  
    * Pink 100 - #ffe8f7 
    * Pink 200 - #ffceef
    * Pink 300 - #ffb4e6 
    * Pink 400 - #ff8ad4 
    * Pink 500 - #d573bb 
    * Pink 600 - #bc4d9a 
  * Purple  
    * Purple 100 - #d9c2f0 
    * Purple 200 - #c1a4e4 
    * Purple 300 - #a885d8 
    * Purple 400 - #9373bd 
    * Purple 500 - #6e4aa7 
    * Purple 600 - #492191 
  * Yellow  
    * Yellow 100 - #fff6b6 
    * Yellow 200 - #ffe45b 
    * Yellow 300 - #ffd200 
    * Yellow 400 - #ffb400 
    * Yellow 500 - #b98f11 
    * Yellow 600 - #9d6e06 
  * Organic  
    * Organic 100 - #f9f5f0 
    * Organic 200 - #f4cfb2 
    * Organic 300 - #c19372 
    * Organic 400 - #714e46 
    * Organic 500 - #62342d 
    * Organic 600 - #482e26 

And for Innovation cup:
* Light mode  
  * background: White: #FFF 
  * primary: Blue: #1976d2 
  * on-primary: White #FFF 
  * secondary: Gray: #b0bec5 
  * on-secondary: Black: #000
  * surface-a: #FFF
  * functional-positive: Green: #328532 
  * functional-negative: Red: #e32800 
  * functional-information: Blue: #4170D8 
  * functional-warning: Yellow: #ffcc00 
* Dark mode  
  * background: Black: #000 
  * primary: Blue: #1976d2 
  * on-primary: White: #fff 
  * secondary: Gray: #808e95 
  * on-secondary: Black: #000 
  * surface-a: #121212 (used for card color background) 
  * functional-positive: Green: #328532 
  * functional-negative: Red:  #e32800 
  * functional-information: Blue: #527edb 
  * functional-warning: Yellow: #ffcc00

**Comment by ludovic35** [comment]
@B3nz01d  Where is the color palette  définition for orange and innovation Thème ?
Where is the système token définition ?

**Comment by ludovic35** [comment]
For this issue, colors are just update with right value
additional evolutions will be done in https://github.com/Orange-OpenSource/ods-ios/issues/439
