### ISSUE TITLE
Text Field demo update

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#429]
**As a User** of the demo app
**I Want** to test the text field and text field variant and 
**So that** when I type some text in and I select a new capitalization option, it will keep the existing text in and I will not have to type in a new text

I it possible to pre-populate the field with an existing content?
if yes, please use the following text:
"A text has been pre-populated. You can add your own in if you want."
when the text field is empty, the current default greyed out text placeholder would stay as is.

This is implemented in the Text Editor variant.

**Comment by ludovic35** [comment]
The capitalization is applied during the input. (base on _.textInputAutocapitalization_)
So the option is "characters capitalize" (all characters automatically converted at the input) The if the option is changed to word capitelize, there is no more action on text already entered, but only new words are capitelized...

**Comment by B3nz01d** [comment]
ok so this proposed update does not work. I'll close the issue
