### ISSUE TITLE
Update ODSBanner

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ods-ios#461]
[] Support only one button user the text
[] In bottom sheet configuration add a picker to select the number of buttons [0..2]
[] Support an assync image (from url and placeholder) 
[] Add a diviser a the bottom
[] Adjust padding
[] Check if figma file is updated
[] Check is DSM is updated

**Comment by B3nz01d** [comment]
@mccart77 should we keep this open for the associated design & DSM tasks?

**Comment by ludovic35** [comment]
> @mccart77 should we keep this open for the associated design & DSM tasks?

Yes sure
