### ISSUE TITLE
Update the button emphasis scale naming

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#464]
The current buttons are using the following scale:
* highest
* high
* medium
* low

In order to align with the web vocabulary updates, the new scale will be:
* high
* medium
* low
* lowest

the correspondence will be applied as follows:
* highest -> high
* high -> medium
* medium -> low
* low -> lowest

**Comment by ludovic35** [comment]
@B3nz01d @mccart77 Need a DSM update before to be moved to Done State
