### ISSUE TITLE
[Bug]: Accessibility Voice over title and header

### ISSUE THREAD

**Issue by Tayebsed93** [Orange-OpenSource/ods-ios#468]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 14 pro Max

### OS Version

iOS 17.0

### App version

0.14.0

### Describe the issue

The page title is a element vocalized or seen on a mobile screen.
It makes navigation easier for everyone: at any time, we know where we are in the application.

iOS headers allow structuring pages providing additional useful information to the accessibility API because VoiceOver can navigate through the headers allowing the user to browse the page faster.

![IMG_2078](https://github.com/Orange-OpenSource/ods-ios/assets/20354434/24f43a25-3c3d-4b47-97b6-74072b936e44)

### Expected Behavior

The title "Orange Design System Demo" must be a header.

Solution : https://a11y-guidelines.orange.com/en/mobile/ios/design/#title-and-header

**Comment by B3nz01d** [comment]
@Tayebsed93  I'll let you confirm this one is ok for you
