### ISSUE TITLE
[Bug]: Thumbnail of card vertical header first not showing

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#499]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

Any

### OS Version

Any

### App version

v0.15.0

### Describe the issue

the thumbnail allways shows the placeholder image instead of the thumbnail.

![MicrosoftTeams-image (2)](https://github.com/Orange-OpenSource/ods-ios/assets/62606284/2a56967f-389f-493a-95e5-7a0d1c1fffe4)

### Expected Behavior

thumbnail of the type or recipe should show.

The page should also always open to a randomize recipe. This should apply to all the cards.

**Comment by Tayebsed93** [comment]
@B3nz01d I think you are on the wrong board. I switched this issue to the ods-ios project board

**Comment by ludovic35** [comment]
@B3nz01d  what we are suppose to display here ?
We always display the placeholder image as example. Could be an async image from url or an image from resources ?

**Comment by B3nz01d** [comment]
this is suppose to show the corresponding icon to the value "iconName": "Restaurant"

**Comment by ludovic35** [comment]
Ok in demo app we use Recipe to configure the component. So we use iconName for the json file (here "Restaurant"). So we load image from ressources. But my question was:
For the component API, do we need to support image from ressources AND image from URL ?

**Comment by ludovic35** [comment]
From meeting @B3nz01d said:
we can have support both. In app use the Restaurant asset only
