### ISSUE TITLE
[Bug][Accessibility] Button - Vocalize the button label

### ISSUE THREAD

**Issue by Tayebsed93** [Orange-OpenSource/ods-ios#546]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 14 pro Max

### OS Version

iOS 17.0

### App version

0.16.0

### Describe the issue

Use case :

Component > Button > Emphase
Activate Voice Over
Set focus on the 'High' button.
High bouton d'emphase, Bouton

### Expected Behavior

The screen reader must read the label 
Example : Activated, Button.'

![IMG_2310](https://github.com/Orange-OpenSource/ods-ios/assets/20354434/760476d7-b819-4e99-a95a-27c4c460ae73)

**Comment by ludovic35** [comment]
@B3nz01d Do you confirm, because we added a specific label on it ?

**Comment by ludovic35** [comment]
Answer : don't and more information fr accessibilité:
remove  .accessibilityLabel("a11y.emphasis_button_hint" <- "\(emphasis.rawValue)")
