### ISSUE TITLE
ODS > Component > Card - Large Side by Side

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#56]
# Large Card with Text & Image Side by Side

The description of this component is described in #25

**Comment by B3nz01d** [comment]
The design of this card needs to be provided

**Comment by ludovic35** [comment]
@mccart77 @Tayebsed93 

Questions: for spec review:
1. For long text in description, do we need to truncate ? 
![image](https://user-images.githubusercontent.com/15976893/216617296-b71954ce-c681-4681-a1eb-61bbea4ee2b3.png)
-> design and accessibility perspective 

2, Do we need to keep image if text description if font is big :  
![image](https://user-images.githubusercontent.com/15976893/216618032-11a4c90f-7c90-4ea4-aea4-bf710822aa0c.png) (Here description is already truncated to by displayed on 2 lines)
-> design and accessibility perspective 

3 , Button emphasis is always low ?

**Comment by B3nz01d** [comment]
1. Image should be kept
2. lenght of text is max 2 lines
3. medium emphasis
4. yes image can be on both sides

**Comment by B3nz01d** [comment]
Card has been renamed "Card Horizontal"

**Comment by Tayebsed93** [comment]
bug ticket : https://github.com/Orange-OpenSource/ods-ios/issues/389
