### ISSUE TITLE
[Bug]: Bars-navigation component accessibility issues

### ISSUE THREAD

**Issue by pya35** [Orange-OpenSource/ods-ios#574]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 14 Plus

### OS Version

17.1.1

### App version

v0.16.0

### Describe the issue

This list is about "**Bars-navigation" component and variant only**. Other common issues are described in dedicated issues.

1. Title on variants screen is "Large Title" or "Title", not relevant.
**Recommandation: Use an explicit title like "Large title demo" or "Title example"**

2. "Standard and "Large" buttons are not linked with the setting label "Size".
**Recommandation: Group label and buttons**

### Expected Behavior
Page 100% accessible

**Comment by pylapp** [comment]
@pya35 Could you please share here some screenshots of the views you are referring? I didn't find the location of theses issues in the app.

**Comment by pya35** [comment]
#744 not delivered yet

**Comment by pya35** [comment]
fixed
