### ISSUE TITLE
[Bug]: ODSButton with low emphasis has incorrect background color with Orange Theme

### ISSUE THREAD

**Issue by yunusun** [Orange-OpenSource/ods-ios#578]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone

### OS Version

iOS 17.2.1

### App version

0.15.0

### Describe the issue

Using the Orange theme, the background color of a `ODSButton` with `.low` emphasis has a background color.

I have added the button as a child of a container with yellow background to make the button background visible.

Light mode:
![Light](https://github.com/Orange-OpenSource/ods-ios/assets/151786098/b0d15259-30bb-46e6-bb88-44abcca47b42)

Dark mode:
![Dark](https://github.com/Orange-OpenSource/ods-ios/assets/151786098/19809827-390d-4a1f-9033-e863014a5709)

### Expected Behavior

According to the design system (https://system.design.orange.com/0c1af118d/p/278734-buttons-shape/b/536b5f) the background color is transparent for a button with .low emphasis.

**Comment by ludovic35** [comment]
After discussion in design meeting: by @B3nz01d  @mccart77  
The background must be transparent 
- Action : Dev update code @ludovic35  @pylapp 
- Action : Design @mccart77  update figma

**Comment by B3nz01d** [comment]
@ludovic35  this cannot be tested in the app right?

**Comment by B3nz01d** [comment]
@yunusun could you confirm this update works for you?

**Comment by ludovic35** [comment]
> @ludovic35 this cannot be tested in the app right?

There is no configuration in app to put the button on a yellow view, so not possible to test with the actual version of the app

**Comment by yunusun** [comment]
Thanks for the fix !
