### ISSUE TITLE
[Bug]: [P1] Common accessibility issue - "Customize" accordion status is not vocalized

### ISSUE THREAD

**Issue by pya35** [Orange-OpenSource/ods-ios#581]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 14 Plus

### OS Version

17.1.1

### App version

v0.16.0

### Describe the issue

For all components that include a "Customize" accordion, the status expanded/collapsed is not vocalized with Voice Over

![image](https://github.com/Orange-OpenSource/ods-ios/assets/105045667/4f73f555-cd28-4ccd-9fcb-20f25245ba37)

### Expected Behavior

Use a native DisclosureGroup

**Comment by pylapp** [comment]
`DisclosureGroup` object won't be sued ebcause it is not the component we want ; we need a kind of bottom sheet and not a collapsable embeded view

**Comment by pya35** [comment]
@pylapp I think the hint is reversed, when sheet is opened, the state is correctly set as "opened" but the hint is "Tap twice to open".
