### ISSUE TITLE
[Bug]: [P1] Common accessibility issue - Button selection status is not vocalized

### ISSUE THREAD

**Issue by pya35** [Orange-OpenSource/ods-ios#583]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 14 Plus

### OS Version

17.1.1

### App version

v0.16.0

### Describe the issue

In all components, button status (selected or not) is not vocalized by Voice Over

![image](https://github.com/Orange-OpenSource/ods-ios/assets/105045667/014ad11b-188f-4099-9ff9-f9fd0e9a7e46)

### Expected Behavior

Use native button to get the selected feedback

**Comment by ludovic35** [comment]
Need to build the vocalisation on ODSFilterChipPicker and ODSChoiceChipPicker. Something like the Segmented Control native component.

**Comment by pya35** [comment]
OK for me on 0.18.0
