### ISSUE TITLE
[Bug]: Color display dark mode

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#6]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 13

### OS Version

iOS 15.1

### App version

v0.1

### Describe the issue

the header bar in the sections is not correct in dark mode
<img src="https://user-images.githubusercontent.com/62606284/151577612-94fba3b9-7a3c-4342-a185-e1ccf31b74e2.png" width="300">

### Expected Behavior

the header text should be blac

k

**Comment by jlchee** [comment]
fixed
