### ISSUE TITLE
ODS > Module > About -1

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#63]
# Requirements
**As a Developer** using the ODS Library
**I want to** be able to create the About page of my App
**So that** I can add this page and the subsequent links in a simple manner respecting the ODS Design and the accessibility requirements

# Content description
Page presentation
* Illustrations (Mandatory and customizable): an illustration of the app (?)  what is the default size format
* App Name (Mandatory)
* App Version (Optional)
* App Description (Optional): (?) what is the max length? Should we use an extended view to show 3 lines?
* Links

Links available from the page:
* privacy policy (Mandatory)
* terms of service (Mandatory)
* Legal information (Optional as a stand alone page) including the 3rd parties libraries -> this content would be either integrated as a dedicated stand alone page or a content integrated inside the terms of service)
* Accessibility statement (Mandatory)
* App news (Optional): this is the App change Log
* Share this App (Optional): A page to propose a link to download the current app
* Feedback (Optional): A page to allow the user to provide feedback on the app or the service
* More Orange Apps (Optional): apps+ links
* Other apps menus (Optional) -> The service creator should be able to add his own menu items if necessary
  *  example for Demo App: Design Guidelines (Specific ODS) 

# Technical requirements
* the module does not need to be created as an outside lib
* the access to the about page should be accessed from the bottom navigation but could be accessed from other locations (see Orange TV app in a "..." plus menu page
* the names of the links should be provided with a translation for other languages. The lib should be provided in 2 languages FR & EN - other languages would be updated by the dev using the lib directly
* (?) is the about icon the same one for every Orange apps? the icon should be included in the lib in that case
* (?) Should the order of the links be standardized 
* (?) Should we allow to put new links on top of the mandatory ones?
* The dev user should be able to add new links after the mandatory list
* by default the page should include the Apps Recirculation module and the dev should be able turn it off as this module could be added elsewhere in the app
* The animation in this page should allow 
  * the header bar only show the action icons, but no title
  * the bounce of the illustration when pulling up (page refresh)
  * the resizing of the image + fade out (to white on light mode and to black on dark mode)
  * when the illustration has disappeared the header "about" is becoming visible

**Comment by ludovic35** [comment]
Q1: Version 0.12.2 (1234566) - DEBUG in debug
Q1: Version 0.12.2 (1234566) in prod version
Q2

**Comment by B3nz01d** [comment]
After discussion with @mccart77  all list items should propose the navigation chevron

**Comment by B3nz01d** [comment]
While investigating the existing usage from orange apps, we found that the list options from the about page should propose along with the title, the following options:
* icon
* subtitle

The current list of items in the demo app should therefore propose these new elements I will propose the following descriptions:


* terms of service (Mandatory): More information on this service usage 
* privacy policy (Mandatory): A clear description on your your personal data management
* Legal information (Optional): More details on the apps context
* Accessibility statement (Mandatory): Conformity of this App to the accessibility requirements
* App news (Optional): Find out the latest features added to this app
* More Orange Apps (Optional): Other Orange Apps you could use
* Rate this app (App specific Menu): Tell us what you think about our app (-> use the real app store link)
* My Reviews: The reviews you have added to existing recipes
* My Recipes: The list of your preferred recipes

@mccart77 if you agree, the customization step should be updated to take into account these new options

**Comment by B3nz01d** [comment]
proposed icons: 
* terms of service: 
![ScreenShot_23-29-06_20 23](https://github.com/Orange-OpenSource/ods-ios/assets/62606284/39c5741a-a73f-4d32-a0ab-658f8b8a5114)

* privacy policy: 
![ScreenShot_23-29-06_20 12](https://github.com/Orange-OpenSource/ods-ios/assets/62606284/cb647eae-7846-4ef5-8152-a33ed04aa5a3)

* Legal information: 
![ScreenShot_23-29-06_20 15](https://github.com/Orange-OpenSource/ods-ios/assets/62606284/4c2cf503-516c-44dd-95a8-c0e4c5233a5f)

* Accessibility statement: 
![ScreenShot_23-29-06_20 10](https://github.com/Orange-OpenSource/ods-ios/assets/62606284/c06e034d-987c-4774-8f26-cd4552a35e6f)

* App news: 
![ScreenShot_23-29-06_20 29](https://github.com/Orange-OpenSource/ods-ios/assets/62606284/fb6a5af0-7ed0-4ed3-9bd9-2c8fd2885e4d)

* More Orange Apps: 
![ScreenShot_23-29-06_20 18](https://github.com/Orange-OpenSource/ods-ios/assets/62606284/5f185426-6c54-43ca-9ebe-ad45948dd0c9)

* Rate this app: 
![ScreenShot_23-29-06_18 47](https://github.com/Orange-OpenSource/ods-ios/assets/62606284/eb575c8f-90e5-4a5a-bd76-62ffce21c110)

* My Reviews: 
![ScreenShot_23-29-06_18 47 001](https://github.com/Orange-OpenSource/ods-ios/assets/62606284/731468c9-dc2e-486d-a471-f5646e5d01ce)

* My Recipes: 
![ScreenShot_23-29-06_20 20](https://github.com/Orange-OpenSource/ods-ios/assets/62606284/1cd688f8-9b13-49a6-8a9e-0c727ce99876)

**Comment by ludovic35** [comment]
We decide that the feedback form is not part of the about component. We will add it to the list of components. When we build this component we will add it in the about as an example. Until this is built here is the text to provide: "form module not available yet, alternatively use your own webform."

**Comment by ludovic35** [comment]
or the app news page, there are 2 cases:

Release version:
What's New: the dev provides a json to be defined and then you would get a view as defined in zeplin
Beta version / Debug / Qualif:  
What's New: same as release version
Change Log: the dev provides a markdown file, then that files is shown

**Comment by ludovic35** [comment]
1. **Summary of remarks and questions and decisions**

- Global Demo of Module: The Customization is not provided in a bottom sheet but in a dedicated page with mode description.

- Copyright  : For now the copyright is linked to the version (if version is not provided, the copyright is not displayed)
A build type can be added for Debu/Qualif versions with this format <Version> - <DEBUG|QUALIF\SOMETHING_ELSE>. This should be ignored for RELEASE
- Share button: the share button is presented only if the url to the store is provided. It is opened outside the app.
- Feedback button : it is added only if an action callback is provided. That means application can do want it wants (open an external link in browser, open a view, navigation in app...). today only a popup is displayed
- ApplicationDescription: Today there is no limit on the longer of the text. The "more" button will be done with a specific component.

- Legal Information: The legal information Item can open what application wants (For demo a view with text is presented)
- Terme of service: Same 
- AppNews: The item is added only if a path to the json file containing the history of Release with associated description is provided. The date of the format will be define by the new component (Today, yesterday, last week, ...)
- A ChangeLog Item can be added for debug or qualif version
- PrivacyPolicy : the item opens a web view if path to html file is provided or a view with collapsable sections is presented if a formatted json is provided (not don for the moment)
- AccessibilityStatement : Need a path to the xml file containig the report (to be done)
- MoreOrangeApps: Need the url to request the list of applications should be presented. For demo point of view a local json is embedded demo application.

2. **Open questions**
Is it possible to change the oder of items in the list ? (priority, index, ...) ?

3. **Technical remarks**
Proposed json format for apps news:
[
    {
        "version": "0.12.0",
        "date": "2023-04-14",
        "news": "Addition of the Bottom Sheet component."
    },
]

**Comment by ludovic35** [comment]
Configuration four About page of the application
1 .Share : 
* use the url of the app on the store 
* Title: Orange Design System iOS
* Content : Text: You will find the Orange Design System Mobile iOS App that provides examples of design implementations in the app store at: <URL>

2. Feedback :
open the github issue tracker

3, List items
To be completed

**Comment by B3nz01d** [comment]
In the Application about pages we should see the following list order:
* Design Guidelines
* Change log (only visible in qualif build)
* Apps News
* Privacy Policy
* Terms and Service
* Accessibility Statement

**Comment by B3nz01d** [comment]
I've listed the following feedbacks here: #422
