### ISSUE TITLE
Update padding in component screen when cards are in one column

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ods-ios#654]
Set font size to:
![image](https://github.com/Orange-OpenSource/ods-ios/assets/15976893/b68d0b75-f1ea-4c8c-822f-e1cab013debc)

Observed in portait:
![image](https://github.com/Orange-OpenSource/ods-ios/assets/15976893/1b40eeea-3933-4133-bff9-1db998a461f6)

Observed in landscape:
![image](https://github.com/Orange-OpenSource/ods-ios/assets/15976893/f75f13f6-c457-4a90-b6e3-c60829a9b298)
Image is croupes

**Comment by ludovic35** [comment]
What we are supose to keep here:

if dynamicFont < acesibilityLavel:

     > Grid of small card 
![GridOfSmallCards](https://github.com/Orange-OpenSource/ods-ios/assets/15976893/510f769c-5108-414a-9e63-838f41faa19f)

else 

   1. Use SmallCard in list
![ListOfSmallCards](https://github.com/Orange-OpenSource/ods-ios/assets/15976893/af9e0601-baa4-41cb-952f-5a99ad3a0d40)

   2. Use CardIlmageFirst in list
![LitOfCardsImageFirst](https://github.com/Orange-OpenSource/ods-ios/assets/15976893/751dd667-0e82-4de1-a72d-d70b9e91879b)

 
fi

**Comment by pya35** [comment]
Expected max zoom level management : 235%

**Comment by ludovic35** [comment]
Max level with Samll Cards
![MaxWithSamllCards](https://github.com/Orange-OpenSource/ods-ios/assets/15976893/b8e411e4-433b-4821-83d3-508b0501f4aa)

Max level with CardImageFirst:
![MaxWithCardImageFirst](https://github.com/Orange-OpenSource/ods-ios/assets/15976893/54d2c484-56a5-4310-aa45-27e688975f20)

**Comment by ludovic35** [comment]
same problème on iPad :
![GrofOfSmallCardOnIpad](https://github.com/Orange-OpenSource/ods-ios/assets/15976893/9c227050-98b5-4e7a-b0b8-ee03329874a6)

**Comment by pya35** [comment]
ok on 0.18.0

**Comment by B3nz01d** [comment]
As discussed with @mccart77 and @ludovic35 we decide that:
* the spacing between 2 cards in higher text size should stay the same as in small text size as in the spacing with the borders
* on the proposition to use the lage card with only the title and subtitles, yes we should use it this way is order to get a card with the right image format.
