### ISSUE TITLE
Add a pull to fresh on all composants screens  using Receipe (DemoApp)

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ods-ios#655]
Already done in ListItem #586 to change recipe

**Comment by B3nz01d** [comment]
I've tested this in the following components:
* banners
* cards (except the small cards)
* list item

@ludovic35 I have a some strange behavior I wanted to check with you before logging a bug:
* it seems the first time I use the pull to refresh it does not work, and then it will on the next iterations. 
I found this in the banner
* some pull to refresh do not work, but I did not find a pattern. This was observed in the cards or in the list item
* I had some content mix upd with the photo of the wrong card
* I also saw a content showing the wrong image until it was updated, it did not go through the loading image switch

**Comment by ludovic35** [comment]
> I've tested this in the following components:
> 
> * banners
> * cards (except the small cards)
> * list item
> 
> @ludovic35 I have a some strange behavior I wanted to check with you before logging a bug:
> 
> * it seems the first time I use the pull to refresh it does not work, and then it will on the next iterations.
>   I found this in the banner
> * some pull to refresh do not work, but I did not find a pattern. This was observed in the cards or in the list item
> * I had some content mix upd with the photo of the wrong card
> * I also saw a content showing the wrong image until it was updated, it did not go through the loading image switch

For the last point, we need to do something to manage the loading state. Today the is nothing for that.
For previous points, i think is is inked to that.
