### ISSUE TITLE
[Bug]: Acessibility Voice Over : order of vocalization on Color screen

### ISSUE THREAD

**Issue by Tayebsed93** [Orange-OpenSource/ods-ios#68]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 13 pro max

### OS Version

iOS 15.2.1

### App version

v0.1

### Describe the issue

Test case :

- From system settings : enable Voice Over
- From the Guidelines tab bar **"Guidelines"**
- Select the color tab **"Colors"**
- Problem with the order of vocalization

### Expected Behavior

The vocalization order of the elements is not logical and understandable

**Suggestion** : [https://a11y-guidelines.orange.com/en/mobile/ios/development/#reading-order](https://a11y-guidelines.orange.com/en/mobile/ios/development/#reading-order)

**For exemple** : Download the mDAN application from the Apple store and select the reading order example

![IMG_D402BB458914-1](https://user-images.githubusercontent.com/20354434/163556059-bef69acb-dc7c-41f2-89dc-abe469346902.jpeg)

**Comment by ludovic35** [comment]
@Tayebsed93I'ma right, but what is the right order ? I can not find specification about that.
@B3nz01d  Do you know, where the order it is specified ?

**Comment by B3nz01d** [comment]
@Tayebsed93  I propose this following reading order, let us know if it is ok for you:
* the user should arrive on the page focused on the title
* the next focus should be the Mode selection
* the next focus is the section title "Core"
* then the focus should be available on the entire color description including the color illustration and it's corresponding text. and the read-out should read in one go for each color (in our case Orange 200 then White 100 then Black 100 ...):
  * the color token name
  * the subname
  * the rgb values
  * the hex value
* then the section title functional
* then the next colores in the same way...

Is this correct?

**Comment by Tayebsed93** [comment]
> @Tayebsed93 I propose this following reading order, let us know if it is ok for you:
> 
> * the user should arrive on the page focused on the title
> * the next focus should be the Mode selection
> * the next focus is the section title "Core"
> * then the focus should be available on the entire color description including the color illustration and it's corresponding text. and the read-out should read in one go for each color (in our case Orange 200 then White 100 then Black 100 ...):
>   
>   * the color token name
>   * the subname
>   * the rgb values
>   * the hex value
> * then the section title functional
> * then the next colores in the same way...
> 
> Is this correct?

It's correct.
Congratulations for the work the order of vocalization is good
