### ISSUE TITLE
[Bug]: Bug Accessibility Voice Over : content changes vocalized on color screen

### ISSUE THREAD

**Issue by Tayebsed93** [Orange-OpenSource/ods-ios#72]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 13 pro max

### OS Version

iOS 15.2.1

### App version

v0.1

### Describe the issue

Test case :

- From system settings : enable Voice Over
- From the Guidelines tab bar **"Guidelines"**
- Select the color tab **"Colors"** and **click**
- Problem with the content changes vocalized.

![IMG_7AC8CD95DAAF-1](https://user-images.githubusercontent.com/20354434/163575532-a792d943-7503-46f1-be82-024048a7ecd2.jpeg)

### Expected Behavior

Verify that using voice navigation, the content changes are vocalized to the user :
- the opening of (pop-up) s vocalized
- the opening of a new screen (UIView) is vocalized by its title
- the change of a part of the screen (such as a fragment that changes) is vocalizede
- horizontal scrolling is vocalized

2. Propose a title to the page [https://a11y-guidelines.orange.com/en/mobile/ios/design/#title-and-header](https://a11y-guidelines.orange.com/en/mobile/ios/design/#title-and-header)

**Suggestion vocalized change** : [https://a11y-guidelines.orange.com/en/mobile/ios/development/#notify-a-content-change](https://a11y-guidelines.orange.com/en/mobile/ios/development/#notify-a-content-change)

**Comment by ludovic35** [comment]
@Tayebsed93 What an how we are suppose to vocalize in this screen ?

**Comment by Tayebsed93** [comment]
@ludovic35 la vocalisation est correct dans l'ensemble
Par contre il n'y a pas de bouton pour fermer
Ce qu'il faudrait c'est guider l'utilisateur afin qu'il sache comment faire pour quitter la "pop-up".
Exemple : 

- Vocaliser explicitement de cette façon : Cliquer 2 fois pour pouvoir quitter l'écran de détail de la couleur

**Comment by Tayebsed93** [comment]
waiting for the new version with the correction
