### ISSUE TITLE
Title is the same for both variants "Progress bar demo", title must be unique.

### ISSUE THREAD

**Issue by pya35** [Orange-OpenSource/ods-ios#724]
Progress indicators : twice the same title for both variants "Progress bar demo", title must be unique and linked to the main content.

Suggestion : "Progress bar demo" & "Loading Spinner demo"

**Comment by Tayebsed93** [comment]
- la doc dit
### Progress bar
### Activity indicators

dans la PR:
"screens.components.progress_indicators.progress_bar.title" = "Progress bar demo";
"screens.components.progress_indicators.activity_bar.title" = "Loading Spinner demo";

![Capture d’écran   2024-05-22 à 19 32 11](https://github.com/Orange-OpenSource/ods-ios/assets/20354434/fa83577b-5a7c-43f3-8a32-ac79d8b3a289)


Est-ce que l'on doit mettre à jour la doc pour appeler Spinner à la place de Activity indicator ?

**Comment by Tayebsed93** [comment]
Activity indicator demo
