### ISSUE TITLE
[Bug]: Bug Accessibility Voice Over  : image used to display text

### ISSUE THREAD

**Issue by Tayebsed93** [Orange-OpenSource/ods-ios#75]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 13 pro max

### OS Version

iOS 15.2.1

### App version

v0.1

### Describe the issue

Test case :

- From system settings : enable voice over
- From the Modules tab bar **"Modules"**
- Select the item **"About"**
- Problem with image
- The image used to display text

![IMG_0390](https://user-images.githubusercontent.com/20354434/163587149-b2c2475f-ac26-409e-839f-1a0c82f31dd0.PNG)

### Expected Behavior

Check that images and graphics elements are not used to display text.(Except for special cases : e.g. logo, captcha, tradename).
Suggestion : Decorative images have no alternative text [https://a11y-guidelines.orange.com/en/mobile/ios/design/#images](https://a11y-guidelines.orange.com/en/mobile/ios/design/#images)

**Comment by B3nz01d** [comment]
@Tayebsed93  not sure to understand the issue, what text are we talking about?

**Comment by Tayebsed93** [comment]
> @Tayebsed93 not sure to understand the issue, what text are we talking about?

@B3nz01d Je fais référence à l'image en entête. (l'image juste en dessous du titre **About**)
C'est une image décorative et celle-ci ne doit pas être vocalisé par le lecteur d'écran.
A noter : depuis la version 0.4.0, l'image a changé c'est une montgolfière.

English : 
I refer to the image in the header. (the image just below the title **About**)
This is a decorative image and should not be vocalized by the screen reader.
Note: since version 0.4.0, the image has changed to a hot air balloon.

**Comment by B3nz01d** [comment]
OK, so the action is to remove this image from the screen reader. Thanks for the clarification
