### ISSUE TITLE
[Bug]: Bug Accessibility : elements magnification

### ISSUE THREAD

**Issue by Tayebsed93** [Orange-OpenSource/ods-ios#76]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 13 pro max

### OS Version

iOS 15.2.1

### App version

v0.1

### Describe the issue

Test case :

- From system settings : maximize the text (310%)
- From the Modules tab bar **"Modules"**
- Select the about tab **"About"**
- Text is truncated

![IMG_7B6E1A54742B-1](https://user-images.githubusercontent.com/20354434/163587721-286266bc-fb83-49f1-a9f9-9359f21be9aa.jpeg)

### Expected Behavior

**Suggestion** : Do not set number of rows to 1 : label.numberOfLines = 0

**Comment by ludovic35** [comment]
So we do it on all text labels ?

**Comment by ludovic35** [comment]
![Simulator Screen Shot - iPhone 13 Pro - 2022-08-24 at 09 43 47](https://user-images.githubusercontent.com/15976893/186360611-91685459-865c-4b23-ad8b-5cf10ba0894f.png)

**Comment by Tayebsed93** [comment]
> 

The capture you show is OK for me
However the ticket was not opened for this screen

**Comment by ludovic35** [comment]
Sorry, You are right. This is the good one :
![Simulator Screen Shot - iPhone 13 Pro - 2022-08-25 at 09 47 29](https://user-images.githubusercontent.com/15976893/186606456-7b9d6cbd-8f05-4bdb-93c8-81d8a36a67be.png)
