### ISSUE TITLE
Update accessibility Statement

### ISSUE THREAD

**Issue by ludovic35** [Orange-OpenSource/ods-ios#764]

**Comment by pya35** [comment]
@pylapp @Tayebsed93 html and xml files (please show me xml rendering before deployment)
[orange-design-system.zip](https://github.com/Orange-OpenSource/ods-ios/files/14463674/orange-design-system.zip)

**Comment by pylapp** [comment]
FYI, three PR submitted:
- https://github.com/Orange-OpenSource/accessibility-statement-lib-ios/pull/17
- https://github.com/Orange-OpenSource/accessibility-statement-lib-ios/pull/15
- https://github.com/Orange-OpenSource/accessibility-statement-lib-ios/pull/13

**Comment by pya35** [comment]
updated HTML with new assessor name [orange-design-system.zip](https://github.com/Orange-OpenSource/ods-ios/files/14492816/orange-design-system.zip)

**Comment by pya35** [comment]
OK for in-app statement.

**Comment by pya35** [comment]
with CSS : [a11y-orange-design-system.zip](https://github.com/Orange-OpenSource/ods-ios/files/14525370/a11y-orange-design-system.zip)

**Comment by pylapp** [comment]
Released in version v1.1.0 (see announcement #790)
