### ISSUE TITLE
[Bug]: Empty state module > Update the Innovation cup illustrations

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#770]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

NA

### OS Version

NA

### App version

v0.18.0 beta dbc02fe

### Describe the issue

the images used in the : 
* 1st use
* User cleared
* Error
* no data
are using the orange version images

### Expected Behavior

a new set of images will be provided to update them with innovation cup specific images

**Comment by pylapp** [comment]
Related to https://github.com/Orange-OpenSource/ods-ios/issues/776
