### ISSUE TITLE
[Bug]: Components > Card - small cards

### ISSUE THREAD

**Issue by mccart77** [Orange-OpenSource/ods-ios#96]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 10

### OS Version

iOS 15.3.1

### App version

0.2.0

### Describe the issue

Small card is not available within this screen
![image](https://user-images.githubusercontent.com/89084974/166458824-4c306601-1a71-4d9a-b2d6-49785c90bed6.png)

### Expected Behavior

Small card should be a viewable option in this screen

**Comment by Gui114um3** [comment]
Add an intermediate page pointing to small and large Card configurator.

**Comment by B3nz01d** [comment]
The same interface as Image card first should be proposed. The user should be seeing a half sized screen card, and should be able to select from the flowing options:
* subtitle: Switch on/off

**Comment by B3nz01d** [comment]
the definition has been clarified for vertical screen and it should be left aligned presented as half screen. the small card size has not yet been defined in horizontal mode, therefore it inherits this half size until this is clarified.

**Comment by ludovic35** [comment]
half screen, so it means there is no spacing between cards in case we want to put two cards in one line ?

**Comment by B3nz01d** [comment]
@Gui114um3 what is the spacing token to use in this case?

**Comment by Gui114um3** [comment]
I suggest to put 2 small cards side by side with spacing-m.

**Comment by B3nz01d** [comment]
@Gui114um3  and would the bottom sheet customization interact only with one card or both at the same time?
