### ISSUE TITLE
[Bug]: Component large cards

### ISSUE THREAD

**Issue by mccart77** [Orange-OpenSource/ods-ios#99]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

iPhone 10

### OS Version

iOS 15.3.1

### App version

0.2.0

### Describe the issue

Large card layout. 

When displaying Image and Title - there is too mush space below the title text (the space below the text should be the same as above)

![image](https://user-images.githubusercontent.com/89084974/166659967-cceedf0e-53ad-4a05-a7b9-2224ab22bd4a.jpeg)

When displaying Image and Title and subtitle  - there is too mush space below the Subtitle text (the space below the subtitle text should be the same as above the title text)

![image](https://user-images.githubusercontent.com/89084974/166660280-5907d18d-664f-4735-aadc-c5b4938acfd5.jpeg)

### Expected Behavior

When only displaying a title - Equal space above the Title and below the title text

When displaying title and subtitle - Equal space above the title and below the subtitle

Refer to the design specification on the DSM staging server: 
https://zeroheight.com/3b9fee398/v/latest/p/62c30f-cards/b/370bca

**Comment by B3nz01d** [comment]
@mccart77  can you confirm that the latest updates outdated this request as it looks correct now?

**Comment by mccart77** [comment]
Yes, I confirm this is correct now
